/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ClickerGame } from "./ClickerGame";
export * as factories from "./factories";
export { ClickerGame__factory } from "./factories/ClickerGame__factory";
